#! /bin/bash
#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Trigger a kernel panic on an instance.

if [[ -z "${1}" ]]; then
  echo "Usage: $0 <instance name>"
  exit 0
fi

echo "Triggering kernel panic on ${1}"
gcloud compute ssh --zone "${ZONE:-us-central1-a}" "${1}" -- \
  sudo systemctl start kpanic --no-block

date="$(date)"
seconds=1
while sleep 1; do
  echo "Panic happened at ${date}: $((seconds++)) seconds ago."
done
