#! /bin/bash
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Start a rolling update to the latest version of the template.

if [[ -z "${1:-}" ]]; then
  echo "Usage: $0 INSTANCE_GROUP"
  exit 0
fi

set -e
set -u

: "${ZONE:=us-central1-a}"

name="$(gcloud compute instance-groups managed describe --zone="${ZONE}" "${1}" --format='value(versions[0].instanceTemplate)')"
gcloud compute instance-groups managed rolling-action start-update --zone="${ZONE}" "${1}" --version=template="${name}"
